"""adupdate column name

Revision ID: 11355610796f
Revises: 86c20a1ad5fa
Create Date: 2024-03-08 20:00:53.552459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11355610796f'
down_revision = '86c20a1ad5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter_username', sa.Text(), nullable=False))
        batch_op.drop_column('twitter_user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter_user_name', sa.TEXT(), nullable=False))
        batch_op.drop_column('twitter_username')

    # ### end Alembic commands ###
