"""add fan model

Revision ID: 2535770f91ee
Revises: 1c91c839bdfd
Create Date: 2024-03-06 20:39:01.362925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2535770f91ee'
down_revision = '1c91c839bdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('interests', sa.String(length=255), nullable=True),
    sa.Column('engagement_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fan')
    # ### end Alembic commands ###
