"""update comment table

Revision ID: 2d1aec759d92
Revises: da93d9c3395d
Create Date: 2024-03-10 02:37:01.263293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1aec759d92'
down_revision = 'da93d9c3395d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_reply', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sentiment', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('sentiment')
        batch_op.drop_column('comment_reply')

    # ### end Alembic commands ###
