"""comment model is updated

Revision ID: 586fef3bc26f
Revises: 2d1aec759d92
Create Date: 2024-03-10 08:00:10.032145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586fef3bc26f'
down_revision = '2d1aec759d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_message', sa.Text(), nullable=True))
        batch_op.alter_column('sentiment',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('comment_reply')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_reply', sa.TEXT(), nullable=False))
        batch_op.alter_column('sentiment',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('reply_message')

    # ### end Alembic commands ###
