"""migration added

Revision ID: da93d9c3395d
Revises: 3f88132cd54c
Create Date: 2024-03-10 01:59:23.438940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da93d9c3395d'
down_revision = '3f88132cd54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('gen_description')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gen_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('gen_description')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gen_description', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
