"""reply msg id added

Revision ID: dd9092234ce5
Revises: 586fef3bc26f
Create Date: 2024-03-10 08:25:30.706101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9092234ce5'
down_revision = '586fef3bc26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_message_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('reply_message_id')

    # ### end Alembic commands ###
