"""Product table update

Revision ID: e1b149012a7e
Revises: 11355610796f
Create Date: 2024-03-09 12:59:57.991170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b149012a7e'
down_revision = '11355610796f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_logo',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('twitter_username',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('twitter_username',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('product_logo',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
